language: node_js

sudo: false

node_js:
- '8'

before_script:
- export TZ=Europe/Warsaw

notifications:
  slack:
    secure: d3psRZs/GDv1Q8diQ5WdBzAQYQTXsxcaQlSInqgwgxG3kcDOGlA6Is/k5VTquWla/oMGw1uLlvn48brxeW1lAWuvbC5fjUDXHoL6e7mQfKXR7dQfOmQWfqDEmDJHR2CD/D0rAdfNmfsL9lZxRf0a80zcHYM0H6u73svb3sT3uHlxXmDtNr6xSB0efUuDrC8LXxO4Q/oovjRHmsfo0jOUPEIPPD7u78gWIIKPS3QylkdZP6cs6LcC7stXr47rVh6txMl1x1pckDBoEwGrZWmsJN1ASq56Uey5zm8Ql89hohb0HVuDqkB5fbZxauylizTelLxalmC+dz5LyWdzCSlUe8I4vRnqM4R7fwnfX09KuH/MzIdr7CzQ7QE5UZk0M56pAcdi5F4KKtlikNrRsPJ9DUFdXLlmrXoBskG7PWIAdznNXb026QBm80CT0a5xAN6n7+ynLp/mSTa74pSPGw9sywUGboNMC7qmLYWK0lmCWuMDSwzb7Zb6MuntFTnD4qnu5C+MPwVGZddJ6TRdcwBcWpm/Yg3zyhT9PFdXFOIhcQVVtwLTn+tLhfvwYXaAdN8t6S6XICGIVERt0zojXVhuKnekvkxi6qSsvTQZnnTImgvljq5IWSOnzjdM+AdBIIUSy9kATGFeaIeMp9RVACCjrpxT0vpC+Rht/i1QvT7c7qg=
